/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */package gui;

import javax.swing.JOptionPane;
import models.User;
import models.Student;
import dao.StudentDAO;
import dao.AttendanceDAO;
import java.sql.SQLException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

public class AttendanceReportsForm extends javax.swing.JFrame {

    private User currentUser;
    private StudentDAO studentDAO;
    private AttendanceDAO attendanceDAO;

    public void setCurrentUser(User user) {
        this.currentUser = user;
        initializeData();
    }

    private void initializeData() {
        studentDAO = new StudentDAO();
        attendanceDAO = new AttendanceDAO();

        initializeComboBoxes();
        setupTable();
        // Set default dates for date range report
        LocalDate today = LocalDate.now();
        jTextField1.setText(today.minusMonths(1).format(java.time.format.DateTimeFormatter.ISO_LOCAL_DATE));
        jTextField2.setText(today.format(java.time.format.DateTimeFormatter.ISO_LOCAL_DATE));
        
        // Initial state: disable student/course specific fields
        jComboBox3.setEnabled(false);
        jComboBox2.setEnabled(false);
        jTextField1.setEnabled(false); // Start Date
        jTextField2.setEnabled(false); // End Date
    }

    private void initializeComboBoxes() {
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Student Summary");
        jComboBox1.addItem("Course Summary");
        jComboBox1.addItem("Date Range Report");

        jComboBox2.removeAllItems();
        List<String> courses = studentDAO.getAllCourses();
        for (String course : courses) {
            jComboBox2.addItem(course);
        }

        jComboBox3.removeAllItems();
        // Load students managed by the current teacher
        List<Student> students = studentDAO.getAllStudents(currentUser.getId());
        for (Student student : students) {
            jComboBox3.addItem(student.toString());
        }
    }

    private void setupTable() {
        String[] columnNames = {"Student ID", "Student Name", "Course", "Total Days", "Present Days", "Attendance %"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Make table read-only
            }
        };
        jTable2.setModel(model);
    }

    public AttendanceReportsForm() {
        initComponents();
        setLocationRelativeTo(null); // Center the form
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                try {
                    goBackToDashboard();
                } catch (SQLException ex) {
                    Logger.getLogger(AttendanceReportsForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("                 Attendance Report");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Report Option "));

        jLabel2.setText("Report type:");

        jLabel3.setText("From:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Student:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("From:");

        jLabel6.setText("  _");

        jButton1.setText("Generate Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(39, 39, 39)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(39, 39, 39)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Student Name", "Course", "Total Days", "Present Days", "Attendance %"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        // TODO add your handling code here:
       String reportType = (String) jComboBox1.getSelectedItem();

        // Enable/disable controls based on report type
        jComboBox3.setEnabled(false); // Student dropdown
        jComboBox2.setEnabled(false); // Course dropdown
        jTextField1.setEnabled(false); // From Date
        jTextField2.setEnabled(false); // To Date

        if ("Student Summary".equals(reportType)) {
            jComboBox3.setEnabled(true);
        } else if ("Course Summary".equals(reportType)) {
            jComboBox2.setEnabled(true);
        } else if ("Date Range Report".equals(reportType)) {
            jTextField1.setEnabled(true);
            jTextField2.setEnabled(true);
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Generate Report button
        generateReport();
    }//GEN-LAST:event_jButton1ActionPerformed
private void generateReport() {
        String reportType = (String) jComboBox1.getSelectedItem();
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0); // Clear existing data
        try {
            if ("Student Summary".equals(reportType)) {
                generateStudentSummaryReport(model);
            } else if ("Course Summary".equals(reportType)) {
                generateCourseSummaryReport(model);
            } else if ("Date Range Report".equals(reportType)) {
                generateDateRangeReport(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error generating report: " + e.getMessage(),
                                         "Report Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(AttendanceReportsForm.class.getName()).log(Level.SEVERE, "Error generating report", e);
        }
    }

    private void generateStudentSummaryReport(DefaultTableModel model) {
        // Filter students by the current teacher
        List<Student> students = studentDAO.getAllStudents(currentUser.getId());

        for (Student student : students) {
            double attendancePercentage = attendanceDAO.getAttendancePercentage(student.getStudentId(), currentUser.getId());

            List<models.Attendance> studentAttendance = attendanceDAO.getAttendanceByStudent(student.getStudentId(), currentUser.getId());
            int totalDays = studentAttendance.size();
            int presentDays = (int) (totalDays * attendancePercentage / 100);

            Object[] row = {
                student.getStudentId(),
                student.getName(),
                student.getCourse(),
                totalDays,
                presentDays,
                String.format("%.2f%%", attendancePercentage)
            };
            model.addRow(row);
        }
    }

    private void generateCourseSummaryReport(DefaultTableModel model) {
        String selectedCourse = (String) jComboBox2.getSelectedItem();
        if (selectedCourse == null) {
            JOptionPane.showMessageDialog(this, "Please select a course!", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Filter students by the current teacher and selected course
        List<Student> students = studentDAO.getAllStudents(currentUser.getId());

        for (Student student : students) {
            if (student.getCourse().equals(selectedCourse)) {
                double attendancePercentage = attendanceDAO.getAttendancePercentage(student.getStudentId(), currentUser.getId());

                List<models.Attendance> studentAttendance = attendanceDAO.getAttendanceByStudent(student.getStudentId(), currentUser.getId());
                int totalDays = studentAttendance.size();
                int presentDays = (int) (totalDays * attendancePercentage / 100);

                Object[] row = {
                    student.getStudentId(),
                    student.getName(),
                    student.getCourse(),
                    totalDays,
                    presentDays,
                    String.format("%.2f%%", attendancePercentage)
                };
                model.addRow(row);
            }
        }
    }

    private void generateDateRangeReport(DefaultTableModel model) {
        String startDateStr = jTextField1.getText().trim();
        String endDateStr = jTextField2.getText().trim();

        if (startDateStr.isEmpty() || endDateStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both start and end dates!",
                                         "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        LocalDate startDate;
        LocalDate endDate;
        try {
            startDate = LocalDate.parse(startDateStr);
            endDate = LocalDate.parse(endDateStr);
        } catch (java.time.format.DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Invalid date format! Use YYYY-MM-DD", "Date Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (startDate.isAfter(endDate)) {
            JOptionPane.showMessageDialog(this, "Start date must be before or equal to end date!", "Date Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Get attendance for the date range, filtered by the current teacher's students
        List<models.Attendance> attendanceList = attendanceDAO.getAttendanceByDateRange(startDate, endDate, currentUser.getId());

        // Group by student and calculate statistics
        List<Student> studentsManagedByTeacher = studentDAO.getAllStudents(currentUser.getId());
        
        // Use a map to store aggregated data for each student
        java.util.Map<String, int[]> studentStats = new java.util.HashMap<>(); // studentId -> [totalDays, presentDays]

        for (models.Attendance attendance : attendanceList) {
            // Ensure the attendance record belongs to a student managed by the current teacher
            boolean isManagedStudent = studentsManagedByTeacher.stream()
                                        .anyMatch(s -> s.getStudentId().equals(attendance.getStudentId()));
            
            if (isManagedStudent) {
                int[] stats = studentStats.getOrDefault(attendance.getStudentId(), new int[]{0, 0});
                stats[0]++; // Increment total days
                if ("Present".equals(attendance.getStatus())) {
                    stats[1]++; // Increment present days
                }
                studentStats.put(attendance.getStudentId(), stats);
            }
        }

        for (Student student : studentsManagedByTeacher) {
            int[] stats = studentStats.get(student.getStudentId());
            if (stats != null && stats[0] > 0) {
                int totalDays = stats[0];
                int presentDays = stats[1];
                double percentage = (double) presentDays / totalDays * 100;
                Object[] row = {
                    student.getStudentId(),
                    student.getName(),
                    student.getCourse(),
                    totalDays,
                    presentDays,
                    String.format("%.2f%%", percentage)
                };
                model.addRow(row);
            }
        }
    }

    private void goBackToDashboard() throws SQLException {
        this.dispose();
        TeacherDashboard dashboard = new TeacherDashboard();
        dashboard.setUserInfo(currentUser);
        dashboard.setVisible(true);
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendanceReportsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // For testing, you might temporarily set a dummy user
                // User dummyUser = new User(); dummyUser.setId(1); dummyUser.setUsername("testteacher"); dummyUser.setRole("Teacher");
                // AttendanceReportsForm form = new AttendanceReportsForm();
                // form.setCurrentUser(dummyUser);
                // form.setVisible(true);
                new LoginForm().setVisible(true); // Always start from login
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
